id: I54078393
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T21:00:13+00:00'
last_modified: '2022-06-08T01:59:29.502350+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC215
  title: 'དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་པར་བཤད་པ་ཐར་ལམ་གསལ་བྱེད། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1840':
      image_group_id: I2PD18540
      title: ''
      total_pages: 598
      order: 1
      base_file: 1840.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
