id: P004567
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:42:04.528741
source_metadata:
  id: bdr:W1AC215
  title: 'དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་པར་བཤད་པ་ཐར་ལམ་གསལ་བྱེད། '
  author: ''
  volumes:
    ae71087b4f8a4fab9b1375b4be1a8c4c:
      image_group_id: I2PD18540
      title: ''
      volume_number: 1
      total_pages: 598
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
